# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nginx:
  labels: 
    - nginx
    - demo

image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

configMap:
  index: base64

nodeSelector: {}
